### ISSUE TITLE
add support for using WMO BUFR4 tables from GitHub

### ISSUE THREAD

**Issue by tomkralidis** [ECCC-MSC/libecbufr#93]
Note that the WMO BUFR tables are now [machine readable on GitHub](https://github.com/wmo-im/BUFR4), it would be valuable to consider having an import utility to generate the objects needed by libeccbufr.  It would be also be valuable to consider using the tables (in [XML](https://github.com/wmo-im/BUFR4/tree/master/xml), or [text](https://github.com/wmo-im/BUFR4/tree/master/txt)) directly (pulling them in at build time).

The XML and text files are always updated live (for dev), and production releases are in https://github.com/wmo-im/BUFR4/releases

**Comment by tomkralidis** [comment]
Note that while the XML and text files are the official releases, we **could** use the release tags of the CSVs (e.g. https://github.com/wmo-im/bufr4/tree/v36).

**Comment by vsouvan** [comment]
changes for reading wmo CSV tables  have been committed.
