### ISSUE TITLE
make problem

### ISSUE THREAD

**Issue by llazcano** [ECCC-MSC/libecbufr#97]
I have problems with make, and installed everything that the guide says.

in Debian GNU/Linux 10 (buster)

ake[2]: *** No rule to make target 'ChangeLog.git', needed by 'all-am'.  Stop.
make[2]: Leaving directory '/root/libecbufr'
make[1]: *** [Makefile:527: all-recursive] Error 1
make[1]: Leaving directory '/root/libecbufr'
make: *** [Makefile:417: all] Error 2

**Comment by beauregardc** [comment]
I have a buster virtual machine which runs a nightly automated build package build of libecbufr, and all it's doing for each build is:

sh reconf
./configure
make

Only thing I can think of is you might be missing a build dependency.

c.
________________________________
From: llazcano ***@***.***>
Sent: Saturday, June 26, 2021 8:19 AM
To: ECCC-MSC/libecbufr ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ECCC-MSC/libecbufr] make problem (#97)


I have problems with make, and installed everything that the guide says.

in Debian GNU/Linux 10 (buster)

ake[2]: *** No rule to make target 'ChangeLog.git', needed by 'all-am'. Stop.
make[2]: Leaving directory '/root/libecbufr'
make[1]: *** [Makefile:527: all-recursive] Error 1
make[1]: Leaving directory '/root/libecbufr'
make: *** [Makefile:417: all] Error 2

**Comment by llazcano** [comment]
Ty.

But my problems is in:

./configure..checking for pkg-config... no
./configure: line 10799: syntax error near unexpected token `CHECK,'
./configure: line 10799: `PKG_CHECK_MODULES(CHECK, check >= 0.9.4, CHECK_AVAILABLE="yes", CHECK_AVAILABLE="no")'

What is bad??

Ty.

**Comment by beauregardc** [comment]
It's a missing build dependency. You need to install the pkg-config package. The configure script probably should fail immediately after the "pkg-config... no" output rather than generating that syntax error output.

c.
________________________________

**Comment by llazcano** [comment]
ty.. but 

apt-get -y install pkg-config
pkg-config ya está en su versión más reciente (0.29-6).
**and the problems continue.**

checking for doxygen... /usr/bin/doxygen
checking for pkg-config... yes
./configure: line 10799: syntax error near unexpected token `CHECK,'
./configure: line 10799: `PKG_CHECK_MODULES(CHECK, check >= 0.9.4, CHECK_AVAILABLE="yes", CHECK_AVAILABLE="no")'

:(

**Comment by llazcano** [comment]
Yes now.
Thank you very much for your help.

Greetings From Chile
